services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postrges
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # volume creation
    networks:
      - airflow_network

volumes:
  postgres-data:

networks:
  airflow_network:
    external: false # Network creation if not exists